@startuml

title __BOMBERMAN's Class Diagram__\n

class bomberman.BombermanGame {
    {static} + HEIGHT : int
    {static} + WIDTH : int
    - canvas : Canvas
    - entities : List<Entity>
    - gc : GraphicsContext
    - stillObjects : List<Entity>
    + createMap()
    {static} + main()
    + render()
    + start()
    + update()
}
bomberman.BombermanGame -up-|> javafx.application.Application

@enduml
